# Generated by Django 3.2.4 on 2025-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_googleadsaccountcreation_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsmartcampaign',
            name='is_political',
            field=models.CharField(default='false', max_length=500),
            preserve_default=False,
        ),
    ]
